-- Add registry-backed module support to learning_path_items
-- This migration adds fields to ground modules in the Source Registry

-- Add content_mode enum type
DO $$ BEGIN
  CREATE TYPE content_mode AS ENUM ('ai_generated', 'registry_backed');
EXCEPTION
  WHEN duplicate_object THEN null;
END $$;

-- Add new columns for registry-backed modules
ALTER TABLE public.learning_path_items 
ADD COLUMN IF NOT EXISTS source_asset_id uuid REFERENCES public.source_registry_assets(id) ON DELETE SET NULL;

ALTER TABLE public.learning_path_items 
ADD COLUMN IF NOT EXISTS source_node_ids uuid[];

ALTER TABLE public.learning_path_items 
ADD COLUMN IF NOT EXISTS content_mode text DEFAULT 'ai_generated' CHECK (content_mode IN ('ai_generated', 'registry_backed'));

ALTER TABLE public.learning_path_items 
ADD COLUMN IF NOT EXISTS last_resolved_at timestamptz;

ALTER TABLE public.learning_path_items 
ADD COLUMN IF NOT EXISTS content_unavailable boolean DEFAULT false;

-- Add index for querying registry-backed modules
CREATE INDEX IF NOT EXISTS learning_path_items_source_asset_id_idx 
ON public.learning_path_items (source_asset_id) WHERE source_asset_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS learning_path_items_content_mode_idx 
ON public.learning_path_items (content_mode);

-- Add comments for documentation
COMMENT ON COLUMN public.learning_path_items.source_asset_id IS 'References the source registry asset used for grounding this module content';
COMMENT ON COLUMN public.learning_path_items.source_node_ids IS 'Array of source_registry_nodes IDs that back this module content';
COMMENT ON COLUMN public.learning_path_items.content_mode IS 'How content is generated: ai_generated (legacy) or registry_backed (grounded in source registry)';
COMMENT ON COLUMN public.learning_path_items.last_resolved_at IS 'When the source content was last resolved/retrieved';
COMMENT ON COLUMN public.learning_path_items.content_unavailable IS 'True if no suitable registry content exists for this module';

-- Note: Existing modules remain ai_generated by default (backwards compatible)
-- New modules created with source_asset_id will be registry_backed

